Repository unikraft/docs, pull requests merged in 2022-08, with the labels that each got.

#89 Release v0.10.0 with accompanying blog post
  content/en/_index.md
  content/en/blog/2022-08-20-unikraft-releases-phoebe.md
  content/en/releases/v0.10.0.md
  static/assets/imgs/posix-socket.svg
Labels: documentation

#94 hack/usoc22: Add structure
  content/en/community/hackathons/usoc22/advanced-app-porting/demo
  content/en/community/hackathons/usoc22/advanced-app-porting/images
  content/en/community/hackathons/usoc22/advanced-app-porting/index.md
  content/en/community/hackathons/usoc22/advanced-app-porting/sol
  content/en/community/hackathons/usoc22/advanced-app-porting/work
  content/en/community/hackathons/usoc22/baby-steps/demo
  content/en/community/hackathons/usoc22/baby-steps/images
  content/en/community/hackathons/usoc22/baby-steps/index.md
  content/en/community/hackathons/usoc22/baby-steps/sol
  content/en/community/hackathons/usoc22/baby-steps/work
  content/en/community/hackathons/usoc22/basic-app-porting/index.md
  content/en/community/hackathons/usoc22/basic-app-porting/sol
  content/en/community/hackathons/usoc22/basic-app-porting/work
  content/en/community/hackathons/usoc22/behind-scenes/demo
  content/en/community/hackathons/usoc22/behind-scenes/images
  content/en/community/hackathons/usoc22/behind-scenes/index.md
  content/en/community/hackathons/usoc22/behind-scenes/sol
  content/en/community/hackathons/usoc22/behind-scenes/work
  content/en/community/hackathons/usoc22/complex-applications/images
  content/en/community/hackathons/usoc22/complex-applications/index.md
  content/en/community/hackathons/usoc22/complex-applications/sol
  content/en/community/hackathons/usoc22/complex-applications/work
  content/en/community/hackathons/usoc22/contributing-to-unikraft/index.md
  content/en/community/hackathons/usoc22/contributing-to-unikraft/sol
  content/en/community/hackathons/usoc22/contributing-to-unikraft/work
  content/en/community/hackathons/usoc22/debugging/demo
  content/en/community/hackathons/usoc22/debugging/images
  content/en/community/hackathons/usoc22/debugging/index.md
  content/en/community/hackathons/usoc22/debugging/sol
  content/en/community/hackathons/usoc22/debugging/work
  content/en/community/hackathons/usoc22/high-performance/index.md
  content/en/community/hackathons/usoc22/high-performance/sol
  content/en/community/hackathons/usoc22/syscall-shim/demo
  content/en/community/hackathons/usoc22/syscall-shim/images
  content/en/community/hackathons/usoc22/syscall-shim/index.md
  content/en/community/hackathons/usoc22/syscall-shim/work
  content/en/community/hackathons/usoc22/testing-unikraft/images
  content/en/community/hackathons/usoc22/testing-unikraft/index.md
Labels: documentation

#92 Remove public folder
  .gitignore
  public/assets/imgs/unikraft-bot-checkpatch.png
  static/assets/imgs/unikraft-bot-assignments.png
  static/assets/imgs/unikraft-concourse-builds.png
Labels: enhancement

#78 Add Makefile build to Getting Started
  content/en/docs/getting-started/_index.md
Labels: documentation, enhancement
