Repository unikraft/docs, pull requests merged in 2022-12, with the labels that each got.

#161 blog: Add announcement for release 0.11 (Janus)
  content/en/_index.md
  content/en/blog/2022-12-02-unikraft-releases-janus.md
  content/en/releases/v0.11.0.md
Labels: documentation

#160 Unikraft on Morello blog post
  content/en/blog/2022-12-01-unikraft-on-morello.md
  static/assets/imgs/morello-unikraft-build-option.png
  static/assets/imgs/morello-unikraft-fvp.png
  static/assets/imgs/morello-unikraft-machine.jpg
Labels: documentation

#162 docs/contributing: Split coding style content
  content/en/docs/contributing/coding-style.md
  content/en/docs/contributing/submitting-changes.md
Labels: documentation, enhancement

#154 imgs: Add background image for 2022 Aachen hackathon
  static/assets/imgs/2022-06-hack-aachen.png
Labels: bug

#152 layout: Change the default website thumbnail
  layouts/_default/baseof.html
Labels: bug

#174 Add `CONTRIBUTING.md` file referencing the website
  CONTRIBUTING.md
Labels: documentation, enhancement

#178 .github: Add configuration file for textlint
  .github/workflows/.textlintrc
Labels: enhancement

#173 github/linter: Ignore md104 rule when inside shortcodes
  .github/workflows/rules/md104.js
Labels: bug

#176 Fix kraft via pip installation step
  content/en/docs/usage/install.md
Labels: enhancement

#157 Add SoCC22 paper
  data/papers.yaml
  static/assets/files/socc2022-slides.pdf
Labels: documentation

#108 docs/getting-started: Add deps for different linux distributions
  content/en/docs/getting-started/_index.md
Labels: documentation, enhancement
