Repository unikraft/docs, pull requests merged in 2022-10, with the labels that each got.

#124 github/linter: Fix sentence end inside backticks
  .github/workflows/rules/md104.js
Labels: bug

#134 hack/munich22: Update registration deadline
  content/en/community/hackathons/2022-10-munich/_index.md
Labels: enhancement

#136 hack/munich22: Add Nitinder Mohan to organizing team
  content/en/community/hackathons/2022-10-munich/_index.md
Labels: enhancement

#133 docs/develop: Add syscall shim layer old docs
  content/en/docs/develop/syscall-shim.md
Labels: documentation, enhancement

#142 hack/munich22: Add contents for intro section
  content/en/community/hackathons/2022-10-munich/intro/index.md
Labels: documentation

#144 hack/munich22: fix wrong symlinks
  content/en/community/hackathons/2022-10-munich/baby-steps/demo
  content/en/community/hackathons/2022-10-munich/baby-steps/sol
  content/en/community/hackathons/2022-10-munich/baby-steps/work
  content/en/community/hackathons/2022-10-munich/debugging/demo
  content/en/community/hackathons/2022-10-munich/debugging/images
  content/en/community/hackathons/2022-10-munich/debugging/sol
  content/en/community/hackathons/2022-10-munich/debugging/work
Labels: bug, enhancement

#145 hackathons: Fix links to libraries in "Complex Applications" session
  content/en/community/hackathons/sessions/complex-applications/content/Work-Items_01.-SQLite-(Tutorial).md
Labels: enhancement

#143 hackathons: Replace "-serial stdio" with "-nographic"
  content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_01.-Tutorial---Reminder:-Building-and-Running-Unikraft.md
  content/en/community/hackathons/sessions/behind-scenes/content/Work-Items_08.-Tutorial:-Arguments-from-Command-Line.md
  content/en/community/hackathons/sessions/debugging/content/Debugging_Using-GDB.md
  content/en/community/hackathons/sessions/debugging/work/01-gdb-tutorial/kvm_gdb_debug
Labels: enhancement
