Repository unikraft/docs, pull requests merged in 2023-10, with the labels that each got.

#339 feat(docs): Add GitLab integration examples
  content/docs/getting-started/integrations/gitlab.mdx
Labels: documentation

#344 bincompat.mdx: Updated the path to syscall-shim
  content/guides/bincompat.mdx
Labels: documentation, enhancement

#345 guides/bincompat.mdx: Fix "binray" typo
  content/guides/bincompat.mdx
Labels: documentation, hacktoberfest

#346 Typos
  content/guides/bincompat.mdx
Labels: documentation, enhancement, hacktoberfest

#348 guides/bitcompat.mdx: Fix typo
  content/guides/bincompat.mdx
Labels: enhancement

#349 bincompat.mdx: Fix "nount" typo
  content/guides/bincompat.mdx
Labels: documentation, enhancement, hacktoberfest

#352 index.mdx: Add missing word
  content/docs/concepts/index.mdx
Labels: documentation, enhancement, kind/hackathon, hacktoberfest

#350 Fixed 'memoty' typo
  content/guides/challenges.mdx
Labels: documentation, kind/hackathon, hacktoberfest

#353 /internals/build-system.mdx: Update link for documentation
  content/docs/internals/build-system.mdx
Labels: documentation, enhancement, kind/hackathon, hacktoberfest

#351 guides/bincompat.mdx: Reshuffle the words order
  content/guides/bincompat.mdx
Labels: documentation, enhancement, kind/hackathon, hacktoberfest

#355 hackathons/sosp-23: Add links to content sessions
  content/hackathons/2023-10-sosp/index.mdx
Labels: documentation, enhancement

#354 release: Add blog post and notes for release 0.15.0
  content/blog/2023-10-22-unikraft-releases-pandora.mdx
  content/releases/v0.15.0.mdx
  src/components/landing-hero.tsx
  static/assets/imgs/hackathon-aveiro-2023-09-15.jpg
  static/assets/imgs/hackathon-vancouver-2023-09-24.jpg
  static/assets/imgs/hacktoberfest-2023-10-21.jpg
  static/assets/imgs/romania-gathering-2023-10-08.jpg
Labels: enhancement
